import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "../styles/globals.css"
import localFont from "next/font/local"
import Script from "next/script"

const sf_Pro = localFont({
  src: [
    {
      path: "../assets/font/SF-Pro-Text-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/font/SF-Pro-Text-RegularItalic.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../assets/font/SF-Pro-Text-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/font/SF-Pro-Text-MediumItalic.otf",
      weight: "500",
      style: "italic",
    },
    {
      path: "../assets/font/SF-Pro-Text-Semibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../assets/font/SF-Pro-Text-SemiboldItalic.otf",
      weight: "600",
      style: "italic",
    },
    {
      path: "../assets/font/SF-Pro-Text-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../assets/font/SF-Pro-Text-BoldItalic.otf",
      weight: "700",
      style: "italic",
    },
  ],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="dark">
      <head>
        <Script
          src="https://open.spotify.com/embed/iframe-api/v1"
          strategy="beforeInteractive"
          async
        />
      </head>
      <body className={`${sf_Pro.className} dark`} suppressHydrationWarning>
        {children}
      </body>
    </html>
  )
}
